//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        [Display(Name = "文章标题")]
        [Required(ErrorMessage = "请输入标题！")]
        public string Title { get; set; }
        [Display(Name = "文章内容")]
        [Required(ErrorMessage = "请输入文章内容！")]
        public string Context { get; set; }
        [Display(Name = "创建时间")]
        public System.DateTime CreateTime { get; set; }
    }
}
