//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authority()
        {
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int Number { get; set; }
        public string AuthorityString { get; set; }
        public Nullable<bool> UserManage { get; set; }
        public Nullable<bool> GameMemberManage { get; set; }
        public Nullable<bool> SignManage { get; set; }
        public Nullable<bool> ContributionManage { get; set; }
        public Nullable<bool> MemberGroupManage { get; set; }
        public Nullable<bool> RelevantManage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
