//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ContributionList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContributionList()
        {
            this.Contribution = new HashSet<Contribution>();
            this.MemberGroupList1 = new HashSet<MemberGroupList>();
            this.SignList1 = new HashSet<SignList>();
        }

        [Display(Name = "贡献表ID")]
        [Required(ErrorMessage = "请输入贡献表ID！")]
        public string ContributionID { get; set; }
        [Display(Name = "类型")]
        [Required(ErrorMessage = "请选择类型！")]
        public string Type { get; set; }
        [Display(Name = "持续时间长度")]
        public Nullable<int> Time { get; set; }
        [Display(Name = "签到表ID")]
        public string SignID { get; set; }
        [Display(Name = "分组表ID")]
        public string MemberGroupID { get; set; }
        [Display(Name = "创建时间")]
        public System.DateTime CreateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribution> Contribution { get; set; }
        public virtual MemberGroupList MemberGroupList { get; set; }
        public virtual SignList SignList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroupList> MemberGroupList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignList> SignList1 { get; set; }
    }
}
