//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contribution
    {
        public int ID { get; set; }
        [Display(Name = "贡献表ID")]
        [Required(ErrorMessage = "请输入贡献表ID！")]
        public string ContributionID { get; set; }
        [Display(Name = "游戏ID")]
        [Required(ErrorMessage = "请输入游戏ID！")]
        public int GameID { get; set; }
        [Display(Name = "总贡献")]
        public Nullable<decimal> AllContribution { get; set; }
        [Display(Name = "分速")]
        public Nullable<decimal> MinSpeed { get; set; }
        public virtual ContributionList ContributionList { get; set; }
        public virtual GameMember GameMember { get; set; }
    }
}
