//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Feedback
    {
        [Display(Name = "留言反馈ID")]
        public int FeedBackID { get; set; }
        [Display(Name = "用户ID")]
        public int UserID { get; set; }
        [Display(Name = "用户昵称")]
        public string UserName { get; set; }
        [Display(Name = "标题")]
        public string Title { get; set; }
        [Display(Name = "留言反馈内容")]
        public string Context { get; set; }
        [Display(Name = "创建时间")]
        public System.DateTime CreateTime { get; set; }
        [Display(Name = "回复内容")]
        public string Reply { get; set; }
    }
}
