//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FillOut
    {
        public int ID { get; set; }
        [Display(Name = "游戏ID")]
        public int GameID { get; set; }
        [Display(Name = "问卷表ID")]
        public string QuestionaryID { get; set; }
        [Display(Name = "问题ID")]
        public string QuestionID { get; set; }
        [Display(Name = "选项ID")]
        public string SelectID { get; set; }
        [Display(Name = "选项值")]
        public string Value { get; set; }
    
        public virtual GameMember GameMember { get; set; }
        public virtual Question Question { get; set; }
        public virtual Questionary Questionary { get; set; }
        public virtual Select Select { get; set; }
    }
}
