//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class GameMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameMember()
        {
            this.Contribution = new HashSet<Contribution>();
            this.MemberGroup = new HashSet<MemberGroup>();
            this.SignInfo = new HashSet<SignInfo>();
            this.FillOut = new HashSet<FillOut>();
        }

        [Display(Name = "游戏ID")]
        public int GameID { get; set; }
        [Display(Name = "游戏昵称")]
        public string GameName { get; set; }
        [Display(Name = "社团权限")]
        public int Authority { get; set; }
        [Display(Name = "加入时间")]
        public System.DateTime JoinDate { get; set; }
        [Display(Name = "是否删除")]
        public Nullable<bool> IsDel { get; set; }
        [Display(Name = "删除时间")]
        public Nullable<System.DateTime> DelTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contribution> Contribution { get; set; }
        public virtual GameAuthority GameAuthority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroup> MemberGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignInfo> SignInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillOut> FillOut { get; set; }
    }
}
