//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MemberGroup
    {
        public int ID { get; set; }
        [Display(Name = "分组表ID")]
        public string MemberGroupID { get; set; }
        [Display(Name = "游戏ID")]
        public int GameID { get; set; }
        [Display(Name = "组名")]
        public string GroupName { get; set; }
    
        public virtual GameMember GameMember { get; set; }
        public virtual MemberGroupList MemberGroupList { get; set; }
    }
}
