//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameClubEntities : DbContext
    {
        public GameClubEntities()
            : base("name=GameClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Contribution> Contribution { get; set; }
        public virtual DbSet<ContributionList> ContributionList { get; set; }
        public virtual DbSet<GameAuthority> GameAuthority { get; set; }
        public virtual DbSet<GameMember> GameMember { get; set; }
        public virtual DbSet<MemberGroup> MemberGroup { get; set; }
        public virtual DbSet<MemberGroupList> MemberGroupList { get; set; }
        public virtual DbSet<SignInfo> SignInfo { get; set; }
        public virtual DbSet<SignList> SignList { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<InformMessage> InformMessage { get; set; }
        public virtual DbSet<FillOut> FillOut { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionary> Questionary { get; set; }
        public virtual DbSet<Select> Select { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<UserOperateRecord> UserOperateRecord { get; set; }
        public virtual DbSet<UserLoginRecord> UserLoginRecord { get; set; }
    }
}
