//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Questionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionary()
        {
            this.FillOut = new HashSet<FillOut>();
            this.Question = new HashSet<Question>();
        }

        [Display(Name = "问卷ID")]
        public string QuestionaryID { get; set; }
        [Display(Name = "问卷标题")]
        [Required(ErrorMessage = "请填写标题")]
        public string Title { get; set; }
        [Display(Name = "问卷简介内容")]
        [Required(ErrorMessage = "请填写内容")]
        public string Context { get; set; }
        [Display(Name = "创建时间")]
        public System.DateTime CreateTime { get; set; }
        [Display(Name = "开始生效时间")]
        public System.DateTime StartTime { get; set; }
        [Display(Name = "结束调查时间")]
        public System.DateTime EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillOut> FillOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
    }
}
