//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SignList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SignList()
        {
            this.ContributionList = new HashSet<ContributionList>();
            this.MemberGroupList = new HashSet<MemberGroupList>();
            this.SignInfo = new HashSet<SignInfo>();
        }
        [Display(Name = "签到表ID")]
        public string SignID { get; set; }
        [Display(Name = "类型")]
        public string Type { get; set; }
        [Display(Name = "是否启用")]
        public bool Active { get; set; }
        [Display(Name = "贡献表ID")]
        public string ContributionID { get; set; }
        [Display(Name = "分组表ID")]
        public string MemberGroupID { get; set; }
        [Display(Name = "开始签到时间")]
        public System.DateTime StartDateTime { get; set; }
        [Display(Name = "结束签到时间")]
        public System.DateTime EndDateTime { get; set; }
        [Display(Name = "创建时间")]
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContributionList> ContributionList { get; set; }
        public virtual ContributionList ContributionList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroupList> MemberGroupList { get; set; }
        public virtual MemberGroupList MemberGroupList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignInfo> SignInfo { get; set; }
    }
}
