//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SignInfo
    {
        public int ID { get; set; }
        [Display(Name = "签到表ID")]
        public string SignID { get; set; }
        [Display(Name = "游戏ID")]
        public int GameID { get; set; }
        [Display(Name = "签到情况")]
        public string SignCondition { get; set; }
        [Display(Name = "签到时间")]
        public Nullable<System.DateTime> SignDatetime { get; set; }
        [Display(Name = "语音情况")]
        public string VoiceCondition { get; set; }
        [Display(Name = "是否请假")]
        public bool IsLeave { get; set; }
        [Display(Name = "处理")]
        public string Deal { get; set; }
    
        public virtual GameMember GameMember { get; set; }
        public virtual SignList SignList { get; set; }
    }
}
