//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfo
    {
        [Display(Name = "用户ID")]
        public int UserID { get; set; }
        [Display(Name = "用户昵称")]
        public string UserName { get; set; }
        [Display(Name = "密码")]
        public string PassWord { get; set; }
        [Display(Name = "权限")]
        public int Authority { get; set; }
        [Display(Name = "图片数据")]
        public byte[] ImageData { get; set; }
        [Display(Name = "图片类型")]
        public string ImageMimeType { get; set; }
        [Display(Name = "删除状态")]
        public Nullable<bool> IsDel { get; set; }
        [Display(Name = "删除时间")]
        public Nullable<System.DateTime> DelTime { get; set; }
    
        public virtual Authority Authority1 { get; set; }
    }
}
