//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserOperateRecord
    {
        public int ID { get; set; }
        [Display(Name = "用户ID")]
        public int UserID { get; set; }
        [Display(Name = "用户昵称")]
        public string UserName { get; set; }
        [Display(Name = "操作内容")]
        public string OperateContext { get; set; }
        [Display(Name = "记录时间")]
        public System.DateTime RecordTime { get; set; }
    }
}
